[package]
name = "fix-lines"
version = "0.1.0"
edition = "2024"
description = "CLI tool to fix line endings, remove empty lines at the end of the file and insert a final new line."

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
